services:
  php-fpm:
    image: php:8.3-fpm
    container_name: php-fpm
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    volumes:
      - ../app:/var/www/html
    environment:
      SYMFONY_ENV: dev

  php-cli-cron:
    build:
      context: ./php-cli
      dockerfile: Dockerfile
    container_name: php-cli-cron
    volumes:
      - ../app:/var/www/html
      - ./crontab:/etc/cron.d
    entrypoint: ["bash", "-c", "chmod 0644 /etc/cron.d/* && crontab /etc/cron.d/symfony-cron && touch /var/log/cron.log && cron && tail -f /var/log/cron.log"]

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ../app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php-fpm

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - "./data/mysql:/var/lib/mysql"
